# Generated by Django 5.2.4 on 2026-09-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBarberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Barbería', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Número con código de país ej: 573001234567', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('imagen_hero', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('horario_texto', models.TextField(blank=True, help_text='Descripción del horario de atención')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración de la Barbería',
            },
        ),
    ]
