# Generated by Django 5.2.4 on 2026-09-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberos', '0001_initial'),
    ]

    operations = [
    ]
